-- Generated by Mocodo 4.2.4

CREATE TABLE ARTICLES (
  PRIMARY KEY (article_code),
  article_code       VARCHAR(42) NOT NULL,
  titre              VARCHAR(42),
  contenu            VARCHAR(42),
  date_publication   VARCHAR(42),
  auteur             VARCHAR(42),
  statut_publication VARCHAR(42),
  vues               VARCHAR(42),
  image_couverture   VARCHAR(42),
  categorie_code     VARCHAR(42) NOT NULL,
  DETENUS            VARCHAR(42),
  utilisateur_code   VARCHAR(42) NOT NULL
);

CREATE TABLE AVOIR (
  PRIMARY KEY (article_code, tag_code),
  article_code VARCHAR(42) NOT NULL,
  tag_code     VARCHAR(42) NOT NULL
);

CREATE TABLE CATEGORIES (
  PRIMARY KEY (categorie_code),
  categorie_code VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  description    VARCHAR(42)
);

CREATE TABLE COMMANDE (
  PRIMARY KEY (commande_code),
  commande_code    VARCHAR(42) NOT NULL,
  numero_commande  VARCHAR(42),
  date_commande    VARCHAR(42),
  statu_commande   VARCHAR(42),
  utilisateur_code VARCHAR(42) NOT NULL,
  COMMANDE         VARCHAR(42),
  facture_code     VARCHAR(42) NOT NULL
);

CREATE TABLE COMMENTAIRES (
  PRIMARY KEY (comment_code),
  comment_code       VARCHAR(42) NOT NULL,
  titre              VARCHAR(42),
  contenu            VARCHAR(42),
  date_commentaire   VARCHAR(42),
  auteur             VARCHAR(42),
  statut_commentaire VARCHAR(42),
  article_code       VARCHAR(42) NOT NULL,
  COMMENTER          VARCHAR(42)
);

CREATE TABLE DEVIS (
  PRIMARY KEY (devis_code),
  devis_code       VARCHAR(42) NOT NULL,
  numero_devis     VARCHAR(42),
  nom_client       VARCHAR(42),
  date_devis       VARCHAR(42),
  validite_devis   VARCHAR(42),
  detail_projet    VARCHAR(42),
  statut_devis     VARCHAR(42),
  utilisateur_code VARCHAR(42) NOT NULL,
  facture_code     VARCHAR(42) NOT NULL
);

CREATE TABLE FACTURE (
  PRIMARY KEY (facture_code),
  facture_code         VARCHAR(42) NOT NULL,
  numero_facture       VARCHAR(42),
  nom_client           VARCHAR(42),
  date_facture         VARCHAR(42),
  date_echeance        VARCHAR(42),
  montant_total        VARCHAR(42),
  detail_projet        VARCHAR(42),
  mode_paiement        VARCHAR(42),
  statut_facture       VARCHAR(42),
  information_paiement VARCHAR(42),
  r                    VARCHAR(42),
  utilisateur_code     VARCHAR(42) NOT NULL
);

CREATE TABLE MESSAGE (
  PRIMARY KEY (contact_code),
  contact_code     VARCHAR(42) NOT NULL,
  pseudo           VARCHAR(42),
  adresse_email    VARCHAR(42),
  sujet            VARCHAR(42),
  message          VARCHAR(42),
  utilisateur_code VARCHAR(42) NOT NULL,
  ENVOYE           VARCHAR(42)
);

CREATE TABLE PRODUIT (
  PRIMARY KEY (produit_code),
  produit_code VARCHAR(42) NOT NULL,
  nom          VARCHAR(42),
  tarif        VARCHAR(42),
  avatar       VARCHAR(42)
);

CREATE TABLE REFERENCE (
  PRIMARY KEY (produit_code, devis_code),
  produit_code VARCHAR(42) NOT NULL,
  devis_code   VARCHAR(42) NOT NULL
);

CREATE TABLE REFERENCES (
  PRIMARY KEY (commande_code, produit_code),
  commande_code VARCHAR(42) NOT NULL,
  produit_code  VARCHAR(42) NOT NULL,
  REFERENCER    VARCHAR(42)
);

CREATE TABLE ROLE (
  PRIMARY KEY (role_code),
  role_code VARCHAR(42) NOT NULL,
  nom       VARCHAR(42)
);

CREATE TABLE TAGS (
  PRIMARY KEY (tag_code),
  tag_code VARCHAR(42) NOT NULL,
  nom      VARCHAR(42)
);

CREATE TABLE UTILISATEURS (
  PRIMARY KEY (utilisateur_code),
  utilisateur_code VARCHAR(42) NOT NULL,
  nom              VARCHAR(42),
  prenom           VARCHAR(42),
  societe          VARCHAR(42),
  pseudo           VARCHAR(42),
  adresse_email    VARCHAR(42),
  mot_de_passe     VARCHAR(42),
  rue              VARCHAR(42),
  ville            VARCHAR(42),
  code_postal      VARCHAR(42),
  date_inscription VARCHAR(42),
  avatar           VARCHAR(42),
  biographie       VARCHAR(42),
  role_code        VARCHAR(42) NOT NULL,
  POSSEDE          VARCHAR(42)
);

ALTER TABLE ARTICLES ADD FOREIGN KEY (utilisateur_code) REFERENCES UTILISATEURS (utilisateur_code);
ALTER TABLE ARTICLES ADD FOREIGN KEY (categorie_code) REFERENCES CATEGORIES (categorie_code);

ALTER TABLE AVOIR ADD FOREIGN KEY (tag_code) REFERENCES TAGS (tag_code);
ALTER TABLE AVOIR ADD FOREIGN KEY (article_code) REFERENCES ARTICLES (article_code);

ALTER TABLE COMMANDE ADD FOREIGN KEY (facture_code) REFERENCES FACTURE (facture_code);
ALTER TABLE COMMANDE ADD FOREIGN KEY (utilisateur_code) REFERENCES UTILISATEURS (utilisateur_code);

ALTER TABLE COMMENTAIRES ADD FOREIGN KEY (article_code) REFERENCES ARTICLES (article_code);

ALTER TABLE DEVIS ADD FOREIGN KEY (facture_code) REFERENCES FACTURE (facture_code);
ALTER TABLE DEVIS ADD FOREIGN KEY (utilisateur_code) REFERENCES UTILISATEURS (utilisateur_code);

ALTER TABLE FACTURE ADD FOREIGN KEY (utilisateur_code) REFERENCES UTILISATEURS (utilisateur_code);

ALTER TABLE MESSAGE ADD FOREIGN KEY (utilisateur_code) REFERENCES UTILISATEURS (utilisateur_code);

ALTER TABLE REFERENCE ADD FOREIGN KEY (devis_code) REFERENCES DEVIS (devis_code);
ALTER TABLE REFERENCE ADD FOREIGN KEY (produit_code) REFERENCES PRODUIT (produit_code);
ALTER TABLE REFERENCES ADD FOREIGN KEY (produit_code) REFERENCES PRODUIT (produit_code);
ALTER TABLE REFERENCES ADD FOREIGN KEY (commande_code) REFERENCES COMMANDE (commande_code);

ALTER TABLE UTILISATEURS ADD FOREIGN KEY (role_code) REFERENCES ROLE (role_code);
